services:
  - type: web
    name: stage297
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: STAGE289_VERIFY_URL
        value: https://stage289.onrender.com/api/verify
